Attempts to fix the publisher forms ... but ..
Currently the paste fixtures that we use for testing the HTML fail with
the following message:

  File
  "/home/co/ckan/local/lib/python2.7/site-packages/paste/fixture.py",
  line 1179, in __init__
      "<select multiple> not yet supported")
      AssertionError: <select multiple> not yet supported

Having looked at it, it would require implementing support in
paste.fixture and getting the PR in and so forth.  Not sure of the best
approach.