Revert "[1607] "Site is down for maintenance" message - now with templates."
This reverts commit 4a3573f78d47225c61b9867633c3a46365af8de6.
It didn't work on prod2 - I got:
[Mon Oct 27 17:51:08 2014] [error] [client 127.0.0.1]
self.app.setup_app_env(environ, start_response)
[Mon Oct 27 17:51:08 2014] [error] [client 127.0.0.1] AttributeError:
'DrupalAuthMiddleware' object has no attribute 'setup_app_env'